name: google_cloud_storage
description: A Dart client for Google Cloud Storage.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  http: ^1.3.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  test: ^1.24.0
  test_utils: any
